### ISSUE TITLE
Update documentation to reflect v7.0.0

### ISSUE THREAD

**Issue by leandroruel** [Blocss/blocss#64]
you need provide a button or area to show the source code of how the component is made in the docs,
this will be useful when we need copy snippets of a certain component.

**Comment by bramsmulders** [comment]
@leandroruel sorry for my VERY late response. 
The docs(gh-pages branch) are severely outdated, the will be updated very soon with the release of Blocss V6

**Comment by bertusgroenewegen** [comment]
blocss rocckss :)

**Comment by bramsmulders** [comment]
It took me looong time, but the docs are updated to reflect version 7
